<?php

// @codingStandardsIgnoreFile

/** @var \Nouvolution\WishlistAjax\Block\WishlistAddto $block */
$isAjaxWishslitEnabled = $block->isAjaxWishlistEnabled();
?>

<?php if ($isAjaxWishslitEnabled) :?>
<script>
    requirejs(['jquery',  'Nouvolution_WishlistAjax/js/wishlist_removeto'],
        function   ($, wishlistRemoveTo) {
            $(document).ready(function() {
               wishlistRemoveTo.initAjaxWishlistRemove({
                    ajaxWishlist: true
                });
            });
        });
</script>
<?php endif; ?>