<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
   <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('SORT') ?></label>
   <select id="sorter" data-role="sorter" class="sorter-options">
      <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
           <option value="<?= /* @escapeNotVerified */ $_key ?>"
              <?php if ($block->isOrderCurrent($_key)): ?>
                   selected="selected"
              <?php endif; ?>
               >
              <?php echo $block->escapeHtml(__($_order)) ?>
           </option>
      <?php endforeach; ?>
   </select>

<!--    <div id="sorter-collapsible" data-role="collapsible" class="filter-options-item">-->
    <!-- <div id="sorter-collapsible" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
        <div data-role="collapsible">
            <div data-role="title" class="filter-options-title sorter-title">SORT</div>
            <div data-role="content" class="sorter-content">
                <ol class="items">
                    <?php //foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                        <li class="item <?php //$block->isOrderCurrent($_key) ? 'selected' : '' ?>">
                            <a href="?product_list_order=<?= /* @escapeNotVerified */ $_key ?>"><?= $block->escapeHtml(__($_order)) ?></a>
                        </li>
                    <?php// endforeach; ?>
                </ol>

            </div>
        </div>
    </div> -->
  <?php if ($block->getCurrentDirection() == 'desc'): ?>
       <a title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
           <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
       </a>
  <?php else: ?>
       <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
           <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
       </a>
  <?php endif; ?>
</div>

<script>
    require(["jquery", "mage/accordion"], function ($) {
        //$("#sorter-collapsible").collapsible({ active: true});
        $(function(){

        });

    });
</script>