<?php
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')):
?>

	<?php
    $_productCollection = $this->getProducts();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');

    $_n41 = $this->helper('Nouvolution\N41\Helper\Data');
    $n41product = $_n41->_products;
	?>
	<div class="main-newarrivals-slider-container container-fluid pt-5 pb-5">
        <div class="row">
            <div class="col">
                <?php
                if ($block->getMode() == 'grid') {
                    $viewMode = 'grid';
                    $image = 'category_page_grid';
                    $showDescription = false;
                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                } else {
                    $viewMode = 'list';
                    $image = 'category_page_list';
                    $showDescription = true;
                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
                }
                $pos = $block->getPositioned();
                ?>

                <?php if($title = $this->getConfig('title')):?>
                    <h1 class="main-newarrivals-heading text-center" data-aos="fade" data-aos-delay="0"><?= $title ?></h1>
                <?php endif; ?>

                <?php if(!$_productCollection->getSize()): ?>
                    <div class="main-newarrivals-slider" data-aos="fade" data-aos-delay="50">
                        <p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
                    </div>
                <?php else: ?>
                    <div class="main-newarrivals-owl owl-carousel" data-aos="fade" data-aos-delay="50">
                        <?php $_collectionSize = $_productCollection->count() ?>
                        <?php $i=0; foreach ($_productCollection as $_product): ?>
                            <div class='item newarrival-slider-item'>
                                <div class="product-item">
                                    <?php // Product Image ?>
                                    <?php
                                    $imgW = $this->getConfig('width');
                                    $imgH = !empty($this->getConfig('height')) ? $this->getConfig('height') : $imgW*1.5;
                                    $frontImg = $n41product->GetProductImage($_product, $imgW);
                                    $swatchImg = $n41product->GetProductImage($_product, $imgW, $imgH, 'swatch_image');
                                    ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" data-simple-id='<?= $frontImg['simpleId'] ?>' tabindex="-1">
                                        <img src='<?= $frontImg['imgUrl']; ?>' alt='<?= $_product->getName(); ?>' width="<?= $imgW; ?>" class="product-front" />
                                        <?php if($swatchImg): ?>
                                            <img src='<?= $swatchImg['imgUrl']; ?>' alt='<?= $_product->getName(); ?>' width="<?= $imgW; ?>"  class="product-swatch" />
                                        <?php endif; ?>
                                    </a>
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name text-center">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>

                                    <?php if( $this->getConfig('show_price') ): ?>
                                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                    <?php endif; ?>
                                    <!--
                            <div class="actions clearfix">
                                <div class="action-inner">
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <ul class="add-to-links">
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <li>
                                            <a href="#"
                                               class="action towishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                            </a>
                                        </li>
                                        <?php endif; ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                        <li><a href="#"
                                           class="action tocompare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            -->
                                    <?php $i++;?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php if (!$block->isRedirectToCartEnabled()) : ?>
                    <script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
                <?php endif; ?>
                    <script>
                        require([
                            'jquery',
                            'mage/mage',
                            'n41vendor'
                        ], function ($) {
                            'use strict';

                            $(".main-newarrivals-owl").owlCarousel({
                                autoPlay : false,
                                responsive:{
                                    0:{
                                        items:3
                                    },
                                    600:{
                                        items:4
                                    },
                                    1000:{
                                        items:5
                                    }
                                },
                                slideSpeed : 500,
                                margin:15,
                                paginationSpeed : 500,
                                rewindSpeed : 500,
                                navigation : true,
                                stopOnHover : true,
                                pagination :false,
                                scrollPerPage:true,
                            });

                        });
                    </script>
                <?php endif; ?>
            </div>
        </div>

	</div>

<?php endif; ?>